# -*- coding: utf-8 -*-
"""Untitled35.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mqKq9FJWg0qaHP8h4-2Ls-aXhiT2_RhU
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

df=pd.read_csv("fremont.csv")
df1=df.copy()
df1.shape

df.columns

df1.info()

df1.isnull().sum()

df1.describe()

df1.duplicated().sum()

if 'Direction' in df1.columns:
    # Encoding the 'Direction' column after stripping spaces
    df['Direction'] = df['Direction'].str.strip().map({'NB': 0, 'SB': 1, 'EB': 2, 'WB': 3})
    print("\nUnique values in 'Direction' column:", df['Direction'].unique())

print("\nColumn data types after processing:")
print(df1.dtypes)

# Splittig the data
x=df.drop(columns=['CyclistCount','Date','Time'])
y=df['CyclistCount']

# Train test split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

lr=LinearRegression()
lr.fit(x_train,y_train)

y_pred=lr.predict(x_test)

r2=r2_score(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)

print(f"R2 score is {r2}")
print(f"MSE is {mse}")
print(f"MAE is {mae}")

# Input function
a=input("")