# -*- coding: utf-8 -*-
"""Untitled37.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KVO8pCHjRGyy3OOpyT_dayMJnOUMmmc1
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from apyori import apriori

import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

# Step 1: Load the dataset
df = pd.read_csv("Market_Basket_Optimisation.csv", header=None)
transactions = df.values.tolist()
transactions = [[item for item in transaction if pd.notna(item)] for transaction in transactions]

# Step 2: Transaction Encoding
te = TransactionEncoder()
te_ary = te.fit(transactions).transform(transactions)
df_encoded = pd.DataFrame(te_ary, columns=te.columns_)

# Step 3: Generate frequent itemsets
frequent_itemsets = apriori(df_encoded, min_support=0.003, use_colnames=True)

# Step 4: Generate association rules
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=3)

# Step 5: Format output similar to your screenshot
for index, row in rules.iterrows():
    antecedents = ', '.join(list(row['antecedents']))
    consequents = ', '.join(list(row['consequents']))
    print(f"Rule {antecedents}-> {consequents}")
    print(f"Support: {row['support']}")
    print(f"confidence: {row['confidence']}")
    print(f"Lift: {row['lift']}")
    print("-" * 30)